site_name: SEBdemo
site_description: Documentation for the SEBdemo 1D surface energy balance model
site_author: Maarten van Reeuwijk
site_url: https://mvreeuwijk.github.io/SEBdemo/

# Repository (optional)
repo_name: SEBdemo
repo_url: https://github.com/mvreeuwijk/SEBdemo
edit_uri: ''  # disable 'Edit this page' links

# Copyright
copyright: Maarten van Reeuwijk

nav:
  - Home: index.md
  - Governing Equations: governing_equations.md
  - Model: model.md
  - License: LICENSE.md

theme:
  name: material
  language: en
  palette:
    primary: light-blue
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  # Core/structure
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html

  # Code and formatting
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tilde

  # Math support (works with MathJax v3 below)
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.v2.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
