# Build and deploy MkDocs site to GitHub Pages
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'site/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build site and publish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install mkdocs mkdocs-material
          fi

      - name: Build site (MkDocs)
        id: build
        run: |
          BUILD_DIR=site
          python -m mkdocs build --strict --clean
          echo "publish_dir=${BUILD_DIR}" >> $GITHUB_OUTPUT

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ steps.build.outputs.publish_dir }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
