name: Deploy MkDocs documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build site and publish
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt"
            python -m pip install -r requirements.txt
          else
            echo "No requirements.txt found — installing mkdocs and a common theme"
            python -m pip install mkdocs mkdocs-material
          fi

      - name: Sanity check (debug)
        run: |
          python --version
          pip --version
          which mkdocs || true
          echo "Listing repo root:"
          ls -la

      - name: Prepare site directory (mkdocs or docs fallback)
        id: prepare_site
        run: |
          set -e
          BUILD_DIR=site
          # Prefer building with mkdocs if config present
          if [ -f mkdocs.yml ] || [ -f mkdocs.yaml ]; then
            echo "mkdocs config found; building site with mkdocs"
            python -m mkdocs build --strict --clean
          elif [ -d docs ]; then
            echo "No mkdocs config found — copying docs/ -> site/ to publish raw markdown/html"
            rm -rf site
            mkdir -p site
            cp -a docs/. site/
          elif [ -d site ]; then
            echo "Using existing site/ directory"
          else
            echo "No mkdocs config, no docs/ and no site/ directory found — aborting"
            exit 1
          fi
          echo "Built/picked site directory:"
          ls -la "${BUILD_DIR}"
          echo "publish_dir=${BUILD_DIR}" >> $GITHUB_OUTPUT

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ steps.prepare_site.outputs.publish_dir }}

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1